type: base
description: 以项目为根

get:
  description: 获取项目列表
  responses:
    200:
      description: 返回项目列表，列表中的每个条目按以下定义：
      body:
        schema: !include schema/project.json
        example: !include example/project.json

post:
  description: 创建新项目，project_id由服务器生成，此处不提供
  body:
    schema: !include schema/project.json
    example: !include example/project.json
  responses:
    200:
      description: 返回新创建的项目
      body:
        schema: !include schema/project.json

/{projectId}:
  uriParameters:
   projectId:
     type: integer
  get:
    description: 获取单个项目
    responses:
      200:
        description: 返回对应的项目
        body:
          schema: !include schema/project.json
          example: !include example/project.json

  post:
    description: 更新项目
    body:
      schema: !include schema/project.json
      example: !include example/project.json
    responses:
      200:
        description: 返回更新后的项目
        body:
          schema: !include schema/project.json

  delete:
    description: 删除项目
    responses:
      200:
        description: 业务删除成功
