#%RAML 0.8
  uriParameters:
   projectId:
     type: integer
   serviceId:
     type: integer
  description: |

  get:
    description: 获取业务规则列表
    responses:
      200:
        description: 返回业务规则列表，列表中的每个条目按以下定义：
        body:
          application/json:
            schema: !include schema/rule.json
            example: !include example/rule.json

  post:
    description: 创建新业务规则，rule_id由服务器生成，此处不需提供
    body:
      application/json:
        schema: !include schema/rule.json
        example: !include example/rule.json
    responses:
      200:
        description: 业务规则创建成功

  /{ruleId}:
    uriParameters:
     ruleId:
       type: integer
    get:
      description: 获取单个业务规则
      responses:
        200:
          description: 返回对应的业务规则
          body:
            application/json:
              schema: !include schema/rule.json
              example: !include example/rule.json

    post:
      description: 更新业务规则
      body:
        application/json:
          schema: !include schema/rule.json
          example: !include example/rule.json
      responses:
        200:
          description: 业务规则更新成功

    delete:
      description: 删除业务规则
      responses:
        200:
          description: 业务规则删除成功
