#%RAML 0.8
  uriParameters:
   projectId:
     type: integer
   serviceId:
     type: integer
  description: |

  get:
    description: 获取定时任务列表
    responses:
      200:
        description: 返回定时任务列表，列表中的每个条目按以下定义：
        body:
          application/json:
            schema: !include schema/schedule.json
            example: !include example/schedule.json

  post:
    description: 创建新定时任务，schedule_id由服务器生成，此处不需提供
    body:
      application/json:
        schema: !include schema/schedule.json
        example: !include example/schedule.json
    responses:
      200:
        description: 定时任务创建成功

  /{scheduleId}:
    uriParameters:
     scheduleId:
       type: integer
    get:
      description: 获取单个定时任务
      responses:
        200:
          description: 返回对应的定时任务
          body:
            application/json:
              schema: !include schema/schedule.json
              example: !include example/schedule.json

    post:
      description: 更新定时任务
      body:
        application/json:
          schema: !include schema/schedule.json
          example: !include example/schedule.json
      responses:
        200:
          description: 定时任务更新成功

    delete:
      description: 删除定时任务
      responses:
        200:
          description: 定时任务删除成功
