#%RAML 0.8
description: |

get:
  description: 获取平台支持的业务类型列表
  responses:
    200:
      description: 返回业务类型列表
      body:
        application/json:
          schema: !include schema/servicetype.json
